version: "3"
services: 
  zabbix-mysql-server:
    image: mysql:5.7 
    container_name: zabbix-mysql-server
    ports: 
      - 23306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix 
    hostname: zabbix-mysql-server
    restart: always
  
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server-mysql
    hostname: zabbix-server-mysql
    depends_on: 
      - zabbix-mysql-server
    environment: 
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=123456
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 10051:10051
    restart: always

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    hostname: zabbix-web-nginx-mysql
    container_name:  zabbix-web-nginx-mysql
    depends_on: 
      - zabbix-mysql-server
      - zabbix-server
    environment: 
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=Asia/Shanghai
    ports: 
      - 8880:8080
    volumes: 
      - ${curDir}/DejaVuSans.ttf:/usr/share/zabbix/assets/fonts/DejaVuSans.ttf
    restart: always
    







